name: Chrome headed
on: push
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headed: true
