name: Chrome headed
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install openvpn          

      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: ./github/workflows/ovpnconnector.ovpn
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headed: true
